# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce202b1871dfed59d460601f9e627563145a0c9cbd3aefda8f29215d7bf8446919aa33344995ffb6ae81bc7609c609512285aa46725c514621c31e2baf9d8ebc

test:
  secret_key_base: 4aa4423fb5e6390ac3661796ee3410c654ea65e00d9bbf01bccf56df8d63b04a900a1e5e8f75ae4d2bbb1f45e25bbf20406539e07067f39c1561299c14c6246a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
